# @/docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # 本番用のDockerfileを使用
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
    container_name: brightofhouse-web
    restart: always
    ports:
      - "3000:3000"
    # volumes は本番では絶対に指定しない
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    networks:
      - app-network

  tunnel:
    image: cloudflare/cloudflared
    container_name: brightofhouse-tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge