services:
  web:
    build:
      context: .
      # ▼ 修正: ローカル開発用のDockerfile.devを参照する
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
    container_name: brightofhouse-web
    command: npm run dev # ローカル開発モード
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - WATCHPACK_POLLING=true
    networks:
      - app-network

  tunnel:
    image: cloudflare/cloudflared
    container_name: brightofhouse-tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge